### ISSUE TITLE
Issue running gulp with fresh clone

### ISSUE THREAD

**Issue by omnius45467** [Shift3/mean#1]
There seems to be an issue running gulp after running 'npm install'. Is this user error? 

https://www.npmjs.com/package/babel-preset-es2015

![screen shot 2016-02-05 at 4 54 55 pm](https://cloud.githubusercontent.com/assets/7232570/12863385/72224800-cc29-11e5-98ff-6a62c27e8209.png)

**Comment by ggoforth** [comment]
@sammyboy45467 what version of node are you running?

**Comment by kennethkoontz** [comment]
Mine appears to work with versions:

```
➜  mean git:(master) ✗ node -v
v5.1.1
➜  mean git:(master) ✗ npm -v
3.3.12
➜  mean git:(master) ✗ gulp -v
[23:40:37] CLI version 3.9.0
[23:40:37] Local version 3.9.0
➜  mean git:(master) ✗ nodemon -v
1.8.1
```

**Comment by omnius45467** [comment]
```
node -v
v5.3.0

npm -v 
v3.5.3

nodemon -v
1.8.1

gulp CLI && Local
3.9.0
```

**Comment by kennethkoontz** [comment]
@sammyboy45467 Are you still having issues with this?

**Comment by omnius45467** [comment]
Fixed this issue. Just forgot to add a .babelrc
`{
  "presets": ["es2015"]
}`

**Comment by ggoforth** [comment]
@sammybody45467 maybe that should be part of the repo then?
